### ISSUE TITLE
demo.js 無法登入

### ISSUE THREAD

**Issue by cfsghost** [lijiarui/websocket-api#13]
<img width="667" alt="failed" src="https://user-images.githubusercontent.com/252072/37513343-c82b2936-293f-11e8-8b8d-221221672d31.png">

**Comment by cfsghost** [comment]
我用舊版產生的 config.json 去跑就成功了！

剛追蹤了一下 source code，似乎是第一次 init 時，不接受空的 deviceInfo，避開後測試後發現，socket server 也不接受空 deviceInfo 的 init command。

這部分的設計理論上應該是如果沒有給 deviceInfo，server 要自動產生並回傳一組。若是這部分設計可以讓 developer 自訂，那之後要補充說明一下如何產生 config.json。

**Comment by xinbenlv** [comment]
Shall be fixed by my PR #14
