### ISSUE TITLE
Response的消息格式里面的字段不一致

### ISSUE THREAD

**Issue by meepo** [lijiarui/websocket-api#2]
目前遇到的返回值，除了MsgType为0或者1的时候，返回来的属性值的命名用的是驼峰形式，其他时候返回来的属性值使用的是蛇形形式。
![image](https://user-images.githubusercontent.com/506666/31488214-a1dcc53a-af02-11e7-9b27-18b3e0e7837f.png)

![1507799494593](https://user-images.githubusercontent.com/506666/31488631-e67b17e0-af03-11e7-9b9c-8d9ac8565645.jpg)

![1507799711500](https://user-images.githubusercontent.com/506666/31488652-fba40f50-af03-11e7-83cb-0c1d53230bc3.jpg)

**Comment by lijiarui** [comment]
以现在返回格式为主。返回内容文档尚未更新。
