### ISSUE TITLE
退出ipad微信后，在服务器上还是显示已登录

### ISSUE THREAD

**Issue by meepo** [lijiarui/websocket-api#3]
在手机上点击退出ipad微信后，然后重启机器人脚本，还是用之前登录的微信号，这时候服务器返回来的msg是已成功登录，要过一段时间大概是十来分钟才可以重新登陆。

**Comment by hupt1989** [comment]
突出ipad后，一般10分钟后服务器上才会退出，闲的吧，退出再登录
